server:
   port: 9094
   
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: flipkartAdmin


  application:
    name: ADMIN-SERVICE
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost  
jwt:
  secret: secretkey456   
  